# Generated by Django 3.2.8 on 2021-10-08 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=30)),
                ('intro', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('member_start', models.IntegerField(default=1)),
                ('member_end', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('difficulty', models.IntegerField(default=0)),
                ('phnum', models.CharField(max_length=13)),
                ('image', models.FileField(null=True, upload_to='image/')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
