# Generated by Django 3.2.8 on 2021-10-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211014_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
