# Generated by Django 3.2.8 on 2021-10-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('date', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diary/')),
            ],
        ),
    ]
