# Generated by Django 3.2.8 on 2021-10-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
